/*
 * DIO_config.h
 *
 *  Created on: Feb 11, 2019
 *      Author: AyetAllah
 */



#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_
#include"DIO_private.h"



/*RANGE :  TO SELECT A CERTAIN DIRECTION ,YOU SHOULD CHOOSE
                                                        1-DIO_PIN_INIT_OUTPUT
                                                        2-DIO_PIN_INIT_INPUT    */

#define DIO_PIN0_Dir  DIO_PIN_INIT_OUTPUT
#define DIO_PIN1_Dir  DIO_PIN_INIT_OUTPUT
#define DIO_PIN2_Dir  DIO_PIN_INIT_OUTPUT
#define DIO_PIN3_Dir  DIO_PIN_INIT_OUTPUT
#define DIO_PIN4_Dir  DIO_PIN_INIT_OUTPUT
#define DIO_PIN5_Dir  DIO_PIN_INIT_OUTPUT
#define DIO_PIN6_Dir  DIO_PIN_INIT_OUTPUT
#define DIO_PIN7_Dir  DIO_PIN_INIT_OUTPUT
#define DIO_PIN8_Dir  DIO_PIN_INIT_OUTPUT
#define DIO_PIN9_Dir  DIO_PIN_INIT_OUTPUT
#define DIO_PIN10_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN11_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN12_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN13_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN14_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN15_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN16_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN17_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN18_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN19_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN20_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN21_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN22_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN23_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN24_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN25_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN26_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN27_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN28_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN29_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN30_Dir DIO_PIN_INIT_OUTPUT
#define DIO_PIN31_Dir DIO_PIN_INIT_OUTPUT


#define DIO_PIN0_VALUE    DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN1_VALUE    DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN2_VALUE    DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN3_VALUE    DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN4_VALUE    DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN5_VALUE    DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN6_VALUE    DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN7_VALUE    DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN8_VALUE    DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN9_VALUE    DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN10_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN11_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN12_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN13_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN14_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN15_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN16_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN17_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN18_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN19_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN20_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN21_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN22_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN23_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN24_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN25_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN26_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN27_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN28_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN29_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN30_VALUE   DIO_PIN_INIT_VALUE_DEFAULT
#define DIO_PIN31_VALUE   DIO_PIN_INIT_VALUE_DEFAULT



#endif /* DIO_CONFIG_H_ */
