/*
 * DIO_config.h
 *
 *  Created on: Feb 11, 2019
 *      Author: AyetAllah
 */



#ifndef GPIO_CONFIG_H_
#define GPIO_CONFIG_H_
#include "GPIO_private.h"



/*RANGE :  TO SELECT A CERTAIN DIRECTION ,YOU SHOULD CHOOSE
                                                        1-DIO_PIN_INIT_OUTPUT
                                                        2-DIO_PIN_INIT_INPUT    */

#define GPIO_PORTA_PIN0_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTA_PIN1_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTA_PIN2_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTA_PIN3_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTA_PIN4_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTA_PIN5_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTA_PIN6_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTA_PIN7_Dir                DIO_PIN_INIT_OUTPUT

#define GPIO_PORTB_PIN0_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTB_PIN1_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTB_PIN2_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTB_PIN3_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTB_PIN4_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTB_PIN5_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTB_PIN6_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTB_PIN7_Dir                 DIO_PIN_INIT_OUTPUT

#define GPIO_PORTC_PIN0_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTC_PIN1_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTC_PIN2_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTC_PIN3_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTC_PIN4_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTC_PIN5_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTC_PIN6_Dir                DIO_PIN_INIT_OUTPUT
#define GPIO_PORTC_PIN7_Dir                DIO_PIN_INIT_OUTPUT

#define GPIO_PORTD_PIN0_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTD_PIN1_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTD_PIN2_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTD_PIN3_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTD_PIN4_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTD_PIN5_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTD_PIN6_Dir                 DIO_PIN_INIT_OUTPUT
#define GPIO_PORTD_PIN7_Dir                 DIO_PIN_INIT_OUTPUT


#define GPIO_PORTA_PIN0_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTA_PIN1_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTA_PIN2_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTA_PIN3_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTA_PIN4_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTA_PIN5_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTA_PIN6_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTA_PIN7_VALUE           DIO_PIN_INIT_VALUE_DEFAULT

#define GPIO_PORTB_PIN0_VALUE          DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTB_PIN1_VALUE          DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTB_PIN2_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTB_PIN3_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTB_PIN4_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTB_PIN5_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTB_PIN6_VALUE           DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTB_PIN7_VALUE           DIO_PIN_INIT_VALUE_DEFAULT

#define GPIO_PORTC_PIN0_VALUE            DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTC_PIN1_VALUE            DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTC_PIN2_VALUE            DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTC_PIN3_VALUE            DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTC_PIN4_VALUE            DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTC_PIN5_VALUE            DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTC_PIN6_VALUE            DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTC_PIN7_VALUE            DIO_PIN_INIT_VALUE_DEFAULT

#define GPIO_PORTD_PIN0_VALUE              DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTD_PIN1_VALUE              DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTD_PIN2_VALUE              DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTD_PIN3_VALUE              DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTD_PIN4_VALUE              DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTD_PIN5_VALUE              DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTD_PIN6_VALUE              DIO_PIN_INIT_VALUE_DEFAULT
#define GPIO_PORTD_PIN7_VALUE              DIO_PIN_INIT_VALUE_DEFAULT



#endif /* GPIO_CONFIG_H_ */
