/*
 * SSD_config.h
 *
 *  Created on: Feb 11, 2019
 *      Author: AyetAllah
 */

#ifndef SSD_CONFIG_H_
#define SSD_CONFIG_H_

#include"SSD_private.h"
#define NUM_SSD    4

#define SSD_CATHODE_TYPE CATHODE
#define SSD_ANODE_TYPE    ANODE

#define SSD_DEFAULT_VALUE  NAN

#define SSD_DEFAULT_STATE  OFF

/*FILL IN ORDER A,B,C,D,E,F,G,ENABLE,TYPE,STATE_DEAFULT_OFF,VALUE_DEAFULT_0*/

static ssdunit SSD_ASNUM[NUM_SSD]={{DIO_PIN0,DIO_PIN1,DIO_PIN2,DIO_PIN3,DIO_PIN4,DIO_PIN5,DIO_PIN6,DIO_PIN7,\
		SSD_CATHODE_TYPE,SSD_DEFAULT_STATE,SSD_DEFAULT_VALUE }\
		,{DIO_PIN0,DIO_PIN1,DIO_PIN2,DIO_PIN3,DIO_PIN4,DIO_PIN5,DIO_PIN6,DIO_PIN31,SSD_CATHODE_TYPE,SSD_DEFAULT_STATE,SSD_DEFAULT_VALUE },\
		{DIO_PIN0,DIO_PIN1,DIO_PIN2,DIO_PIN3,DIO_PIN4,DIO_PIN5,DIO_PIN6,DIO_PIN30,SSD_CATHODE_TYPE,SSD_DEFAULT_STATE,SSD_DEFAULT_VALUE },\
		{DIO_PIN0,DIO_PIN1,DIO_PIN2,DIO_PIN3,DIO_PIN4,DIO_PIN5,DIO_PIN6,DIO_PIN29,SSD_CATHODE_TYPE,SSD_DEFAULT_STATE,SSD_DEFAULT_VALUE }};








#endif /* SSD_CONFIG_H_ */
